Repository kbojarowska/SkinResque, pull requests merged in 2022-12, with the labels that each got.

#65 OpenAPI documentation
  .gitignore
  skin-resque-api/domain/models/Palette.ts
  skin-resque-api/domain/models/index.ts
  skin-resque-api/domain/schemas/Pallete.ts
  skin-resque-api/domain/shared/index.ts
  skin-resque-api/domain/shared/types.ts
  skin-resque-api/index.ts
  skin-resque-api/swagger.yaml
Labels: feature, BE

#71 created upload file component
  skin-resque-frontend/package-lock.json
  skin-resque-frontend/package.json
  skin-resque-frontend/src/components/UploadFile/UploadFile.js
  skin-resque-frontend/src/components/UploadFile/UploadFile.scss
Labels: feature, FE

#86 Fixed structure of cosmetics page, navbar improvement
  skin-resque-frontend/public/images/bg-cosmetics.svg
  skin-resque-frontend/src/App.js
  skin-resque-frontend/src/App.scss
  skin-resque-frontend/src/components/Navbar/Navbar.scss
  skin-resque-frontend/src/index.scss
  skin-resque-frontend/src/pages/Cosmetics/CosmeticsCatalogue/CosmeticsCatalogue.js
  skin-resque-frontend/src/pages/Cosmetics/CosmeticsCatalogue/CosmeticsCatalogue.scss
  skin-resque-frontend/src/pages/Cosmetics/RecipeDetails/RecipeDetails.js
  skin-resque-frontend/src/pages/Cosmetics/RecipeDetails/RecipeDetails.scss
  skin-resque-frontend/src/pages/RecipeDetails/RecipeDetails.scss
Labels: improvement, FE

#88 fixed import in cosmetics pages
  skin-resque-frontend/src/pages/Cosmetics/CosmeticsCatalogue/CosmeticsCatalogue.js
  skin-resque-frontend/src/pages/Cosmetics/RecipeDetails/RecipeDetails.js
Labels: bug, FE

#96 srq-66-swagger-ui-for-api-look-up
  .gitignore
  dist/favicon-16x16.png
  dist/favicon-32x32.png
  dist/index.css
  dist/oauth2-redirect.html
  dist/swagger-initializer.js
  dist/swagger-ui-bundle.js
  dist/swagger-ui-bundle.js.map
  dist/swagger-ui-es-bundle-core.js
  dist/swagger-ui-es-bundle-core.js.map
  dist/swagger-ui-es-bundle.js
  dist/swagger-ui-es-bundle.js.map
  dist/swagger-ui-standalone-preset.js
  dist/swagger-ui-standalone-preset.js.map
  dist/swagger-ui.css
  dist/swagger-ui.css.map
  dist/swagger-ui.js
  dist/swagger-ui.js.map
  index.html
Labels: documentation, BE
