Repository kbojarowska/SkinResque, pull requests merged in 2022-11, with the labels that each got.

#10 Schemas, models, initialization script
  skin-resque-api/.gitignore
  skin-resque-api/.prettierrc.json
  skin-resque-api/README.md
  skin-resque-api/build/index.js
  skin-resque-api/index.mts
  skin-resque-api/index.ts
  skin-resque-api/infrastructure/models/Cosmetic.mts
  skin-resque-api/infrastructure/models/Pallete.mts
  skin-resque-api/infrastructure/models/User.mts
  skin-resque-api/infrastructure/models/index.ts
  skin-resque-api/infrastructure/schemas/Cosmetics.mts
  skin-resque-api/infrastructure/schemas/Pallete.mts
  skin-resque-api/infrastructure/schemas/User.mts
  skin-resque-api/infrastructure/schemas/index.ts
  skin-resque-api/infrastructure/shared/constatns.mts
  skin-resque-api/package-lock.json
  skin-resque-api/package.json
  skin-resque-api/scripts/create_db.mts
  skin-resque-api/scripts/types.ts
  skin-resque-api/tsconfig.json
Labels: feature

#33 Abstraction, change of stucture
  skin-resque-api/domain/constants.ts
  skin-resque-api/domain/models/Cosmetic.ts
  skin-resque-api/domain/models/Pallete.ts
  skin-resque-api/domain/models/User.ts
  skin-resque-api/domain/models/index.ts
  skin-resque-api/domain/models/types.ts
  skin-resque-api/domain/schemas/Cosmetics.ts
  skin-resque-api/domain/schemas/Pallete.ts
  skin-resque-api/domain/schemas/User.ts
  skin-resque-api/domain/schemas/index.ts
  skin-resque-api/index.mts
  skin-resque-api/index.ts
  skin-resque-api/infrastructure/database_abstraction/Dba.ts
  skin-resque-api/infrastructure/database_abstraction/types.ts
  skin-resque-api/infrastructure/models/Cosmetic.mts
  skin-resque-api/infrastructure/models/Pallete.mts
  skin-resque-api/infrastructure/models/User.mts
  skin-resque-api/infrastructure/models/index.ts
  skin-resque-api/infrastructure/schemas/index.ts
  skin-resque-api/package-lock.json
  skin-resque-api/package.json
  skin-resque-api/scripts/create_db.ts
Labels: feature, BE

#41 Added pagination component
  skin-resque-frontend/src/components/Pagination/Pagination.js
  skin-resque-frontend/src/components/Pagination/Pagination.scss
Labels: feature, FE

#43 created cosmetics catalogue template
  skin-resque-frontend/public/images/pink-spot.png
  skin-resque-frontend/public/images/rosemary-sprig.png
  skin-resque-frontend/public/images/small-pink-dots.png
  skin-resque-frontend/public/images/yellow-spot.png
  skin-resque-frontend/src/pages/RecipeDetails/RecipeDetails.js
  skin-resque-frontend/src/pages/RecipeDetails/RecipeDetails.scss
Labels: feature, FE

#46 created recipe page
  skin-resque-frontend/public/images/cream.png
  skin-resque-frontend/src/components/Heading/Heading.js
  skin-resque-frontend/src/components/Text/Text.js
  skin-resque-frontend/src/pages/RecipeDetails/RecipeDetails.js
  skin-resque-frontend/src/pages/RecipeDetails/RecipeDetails.scss
Labels: feature, FE

#39 Make upper part of front page
  skin-resque-frontend/public/images/color-test.png
  skin-resque-frontend/public/images/conifer-bush.png
  skin-resque-frontend/public/images/cosmetic-recipes.png
  skin-resque-frontend/public/images/front-page-skin-photo.jpg
  skin-resque-frontend/public/images/skintype-test.png
  skin-resque-frontend/public/images/water-drops.png
  skin-resque-frontend/src/pages/FrontPage/FrontPage.js
  skin-resque-frontend/src/pages/FrontPage/FrontPage.scss
Labels: feature, FE

#37 created bottom part of frontpage
  skin-resque-frontend/package-lock.json
  skin-resque-frontend/package.json
  skin-resque-frontend/public/images/dots.png
  skin-resque-frontend/public/images/rosemary.jpg
  skin-resque-frontend/src/pages/FrontPage/FrontPage.js
  skin-resque-frontend/src/pages/FrontPage/FrontPage.scss
Labels: feature, FE

#64 Created and attached types to models and schemas
  skin-resque-api/domain/models/Cosmetic.ts
  skin-resque-api/domain/models/Pallete.ts
  skin-resque-api/domain/models/User.ts
  skin-resque-api/domain/models/index.ts
  skin-resque-api/domain/models/types.ts
  skin-resque-api/domain/schemas/Cosmetics.ts
  skin-resque-api/domain/schemas/Pallete.ts
  skin-resque-api/domain/schemas/User.ts
  skin-resque-api/domain/shared/index.ts
  skin-resque-api/domain/shared/types.ts
Labels: feature, BE

#63 User schema now references cosmetics instead of owning them directly
  skin-resque-api/domain/schemas/User.ts
Labels: improvement, BE
