Repository kbojarowska/SkinResque, pull requests merged in 2023-01, with the labels that each got.

#90 created color pallete info page
  skin-resque-frontend/src/App.js
  skin-resque-frontend/src/pages/ColorPalette/Info.js
  skin-resque-frontend/src/pages/ColorPalette/Info.scss
Labels: feature, FE

#74 API Routes implementation
  skin-resque-api/domain/constants.ts
  skin-resque-api/domain/models/index.ts
  skin-resque-api/domain/schemas/Cosmetics.ts
  skin-resque-api/domain/schemas/User.ts
  skin-resque-api/domain/shared/index.ts
  skin-resque-api/domain/shared/types.ts
  skin-resque-api/index.ts
  skin-resque-api/infrastructure/database_abstraction/Dba.ts
  skin-resque-api/infrastructure/database_abstraction/index.ts
  skin-resque-api/infrastructure/database_abstraction/types.ts
  skin-resque-api/infrastructure/repository/cosmetics/getCosmeticOne.ts
  skin-resque-api/infrastructure/repository/cosmetics/getCosmeticsAll.ts
  skin-resque-api/infrastructure/repository/cosmetics/getCosmeticsRandom.ts
  skin-resque-api/infrastructure/repository/cosmetics/index.ts
  skin-resque-api/infrastructure/repository/shared.ts
  skin-resque-api/infrastructure/repository/user/addPalette.ts
  skin-resque-api/infrastructure/repository/user/createUser.ts
  skin-resque-api/infrastructure/repository/user/deleteUser.ts
  skin-resque-api/infrastructure/repository/user/getUserOne.ts
  skin-resque-api/infrastructure/repository/user/index.ts
  skin-resque-api/infrastructure/repository/user/removePalette.ts
  skin-resque-api/infrastructure/repository/user/removedSavedCosmetic.ts
  skin-resque-api/infrastructure/repository/user/saveCosmetic.ts
  skin-resque-api/infrastructure/repository/user/updateUser.ts
  skin-resque-api/package-lock.json
  skin-resque-api/package.json
  skin-resque-api/routes/cosmetics.ts
  skin-resque-api/routes/users.ts
  skin-resque-api/scripts/create_db.ts
  skin-resque-api/scripts/types.ts
  skin-resque-api/swagger.yaml
  skin-resque-api/tsconfig.json
Labels: feature, BE

#106 added cosmetics json
  skin-resque-api/scripts/cosmetics.json
Labels: BE
